config/routes.rb
Rails.application.routes.draw do
 
  #get 'log_outdoor_climbs/new'
  #get 'log_outdoor_climbs/create'
  devise_for :users

  root 'pages#index'
  get 'pages/index'
  get '/gallery', to: 'pages#gallery'

  get '/climbingmap', to: 'pages#climbingmap'
 
  get '/analytics', to: 'pages#analytics'

  get '/timer', to: 'pages#timer'

  resources :log_outdoor_climbs, only: [:index, :new, :create, :edit, :update, :destroy, :show, :display] do
    collection do
      get :filter
    end
    member do
      delete :destroy_outdoor_climbing
    end
  end

  resources :individual_outdoor_climbs, only: [:index, :new, :create, :update, :destroy]

  # resources :images, only: [:index, :new, :show, :create, :destroy, :display]

end

app/controllers/log_outdoor_climbs_controller.rb
class LogOutdoorClimbsController < ApplicationController
  
  def index
    @log_climbs = OutdoorClimbing.order(date: :desc)
    
    
  end
 

  def edit
    @log_climb = OutdoorClimbing.find(params[:id])
  end


  def update
    @log_climb = OutdoorClimbing.find(params[:id])
    
    if @log_climb.update(log_climb_params)
      redirect_to log_outdoor_climbs_path, notice: "Climb updated successfully!"
    else
      render :edit
    end
  end


  def new
    @individual_outdoor_climbs = IndividualOutdoorClimb.all
    @log_climb = OutdoorClimbing.new
    @log_climbs = OutdoorClimbing.all

    if params[:outdoor_climbing].present? && params[:outdoor_climbing][:main_image].present?
      @log_climb.main_image.attach(params[:outdoor_climbing][:main_image])
    end

  end

  def destroy
    @log_climb = OutdoorClimbing.find(params[:id])
    @log_climb.destroy
    
    redirect_to log_outdoor_climbs_url, notice: "Your log was successfully deleted."
  end
  
  def display
    @log_climb = OutdoorClimbing.find(params[:id])
    @log_climbs = OutdoorClimbing.all
    @log_climb.main_image.attach(params[:outdoor_climbing][:main_image])
  end


  def create
    @log_climb = current_user.log_climbs.build(log_climb_params)
  
    if @log_climb.save
      redirect_to log_outdoor_climbs_url, notice: "Climb logged successfully!"
    else
      render :new , alert: "Climb could not be logged"
    end
  end

  def filter
    @climbing_type = params[:climbing_type]
    
    if @climbing_type == 'all'
      @log_climbs = OutdoorClimbing.order(date: :desc)
    else
      @log_climbs = OutdoorClimbing.where(climbing_type: @climbing_type).order(date: :desc)
    end
  
    render :index
  end

  def show
    @log_climb = OutdoorClimbing.find(params[:id])
  end

  # def update_image
  #   @log_climb =  # Assuming you have a current_user method
    
  #   if @user.avatar.attach(params[:avatar])
  #     flash[:notice] = "Avatar updated successfully"
  #   else
  #     flash[:alert] = "Error updating avatar"
  #   end
    
  #   redirect_to edit_user_path(@user) # Assuming you have an edit_user_path
  # end

  private

  def log_climb_params
    params.require(:outdoor_climbing).permit(:date, :climbing_type, :location, :main_image, :longitude, :latitude, individual_outdoor_climbs_attributes:[:id, :climb_name, :grade, :climbing_style, :tick, :notes, :climbing_partner, :_destroy])
  end


end

# def acceptable_image
#   return unless main_image.attached?
#   unless main_image.blob.byte_size <= 1.megabyte
#     errors.add(:main_image, "is too big")
#   end
#   acceptable_types = ["image/jpeg", "image/png"]
#   unless acceptable_types.include?(main_image.content_type)
#     errors.add(:main_image, "must be a JPEG or PNG")
#   end
# end

app/helpers/log_outdoor_climbs_helper.rb
module LogOutdoorClimbsHelper
end

app/views/log_outdoor_climbs/_displayrecent.html.erb
<% if user_signed_in? %>
  <div class="container">
    <div class="row">
      <% log_climbs.each_with_index do |log_climb, index| %>
        <% if log_climb.main_image.attached? && index < 3 %>
          <div class="col-md-4 mb-4">
            <div class="card">
              <%= image_tag log_climb.main_image, class: "card-img-top" %>
              <div class="card-body">
                <h5 class="card-title"><%= log_climb.date %></h5>
                <p class="card-text"><%= log_climb.location %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/log_outdoor_climbs/_form.html.erb
<h1>Log Outdoor Climbing Session</h1>
<%# <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }<br> %> 
<%# <%= link_to 'Home', new_user_session_path =%> %>
<%= form_with(model: @log_climb, url: log_outdoor_climbs_path) do |f| %>
  <div class="field">
    <%= f.label :date, 'When did you go climbing?' %>
    <%= f.date_field :date %>
  </div>

  <div class="field">
    <%= f.label :climbing_type, 'Select Climbing Style' %>
    <%= f.select :climbing_type, ['Sport', 'Trad', 'Bouldering'], {}, class: 'form-control' %>

  </div>

  <div class="field">
    <%= f.label :location, 'Where did you go climbing?' %>
    <%= f.text_field :location %>
  </div>
  

  <div class="individual_outdoor_climbs">
    <%= f.fields_for :individual_outdoor_climbs do |individual_outdoor_climb| %>
        <div class="nested-fields">
            <div class="field">
                <%= f.label :climb_name%>
                <%= f.text_area :climb_name%>
            </div>
        
            <div class="field">
                <%= f.label :grade%>
                <%= f.text_area :grade%>
            </div>

            <div class="field">
                <%= f.label :climbing_style%>
                <%= f.text_area :climbing_style%>
            </div>

            <div class="field">
                <%= f.label :tick%>
                <%= f.check_box :tick%>
            </div>

            <div class="field">
                <%= f.label :notes%>
                <%= f.text_area :notes%>
            </div>

            <div class="field">
                <%= f.label :climbing_partner %>
                <%= f.text_area :climbing_partner %>
            </div>

    </div>
  
    <% end %>
  </div>
<%= link_to_add_association "add climb", f, :individual_outdoor_climbs, data: {association_insertion_node: '.individual_outdoor_climbs', association_insertion_method: :append} %>
    


<%= f.submit "Save Climb", class:"btn-primary border-0 rounded-pill shadow p-3" %>
<% end %>
<br>

app/views/log_outdoor_climbs/_individual_outdoor_climb_fields.html.erb
<%# <main> %>
    <%# <section class="py-5 text-left container"> %>
      <%# <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto"> %>
          <%# <p>
        <!-- Nested Form for f -->
        <div class="nested-fields">
            <%= f.label :climb_name%>
            <%# <%= f.text_field :climb_name   %> 
            <%# <%= f.label :tick%>
            <%# <%= f.check_box :tick%> 
            <%# <%= f.label :grade%>
            <%# <%= f.text_field :grade%> 
            <%# <br> %>

            <%# <%= f.label :climbing_style%> 
            <%# <%= f.text_field :climbing_style%> 
          
            <%# <%= f.label :climbing_partner %> 
            <%# <%= f.text_field :climbing_partner %> 

            <%# <%= f.label :notes%>
            <%# <%= f.text_field :notes%> 
            
            <%# <%= f.hidden_field :_destroy %> 
            <%# <%= link_to_remove_association "Delete", f %> 
        <%# </p> %>

<main>
    <section class="py-5 text-left container">
        <!-- <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto"> -->

        <!-- Nested Form for f -->
        <div class="nested-fields">
            <table class="table table-bordered">
                <tr>
                    <td class="col-md-2">
                        <%= f.label :climb_name, class: "form-label" %>
                        <%= f.text_field :climb_name, class: "form-control" %>
                    </td>
                    <td class="col-md-2">
                        <%= f.label :grade, class: "form-label" %>
                        <%= f.text_field :grade, class: "form-control" %>
                    </td>
                    <td class="col-md-2">
                        <%= f.label :climbing_style, class: "form-label" %>
                        <%= f.text_field :climbing_style, class: "form-control" %>
                    </td>
                    <td class="col-md-2">
                        <%= f.label :climbing_partner, class: "form-label" %>
                        <%= f.text_field :climbing_partner, class: "form-control" %>
                    </td>
                    <td class="col-md-2">
                        <%= f.label :notes, class: "form-label" %>
                        <%= f.text_field :notes, class: "form-control" %>
                    </td>
                    <td class="col-md-2">
                        <%= f.hidden_field :_destroy %>
                        <%= link_to_remove_association "Delete", f, class: "btn btn-danger btn-sm mt-2" %>
                    </td>
                </tr>
            </table>
        </div>
    </section>
</main>


    

app/views/log_outdoor_climbs/_map_climbs.html.erb
<head>
<meta charset="utf-8">
<title>Display a map on a webpage</title>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
<link href="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.js"></script>
<style>
body { margin: 0; padding: 0; }
#map { position: absolute; top: 0; bottom: 0; width: 100%; }
</style>
</head>
<body>
<div id="map"></div>
<script>
	mapboxgl.accessToken = 'pk.eyJ1IjoiYWZzbWl0aDEyMyIsImEiOiJjbG9pdTIyaGsxcHd3MnNydzltZnl2Y2Q2In0.uNEZOI46PYjl40gzZ0U2vw';
const map = new mapboxgl.Map({
container: 'map', // container ID
// Choose from Mapbox's core styles, or make your own style with Mapbox Studio
style: 'mapbox://styles/mapbox/streets-v12', // style URL
center: [-74.5, 40], // starting position [lng, lat]
zoom: 9 // starting zoom
});
</script>
 
</body>

app/views/log_outdoor_climbs/edit.html.erb
<main>
    <section class="py-5 text-center container">
        <!-- <div class="row py-lg-5"> -->
        <div class="col-lg-8 mx-auto">
            <h1 class="fw-light">Log a new Outdoor Climbing Session</h1>

            <%= form_with(model: @log_climb, url: log_outdoor_climb_path(@log_climb), method: :patch, class: "mt-4") do |f| %>
                <div class="mb-3">
                    <%= f.label :date, 'When did you go climbing?', class: "form-label" %>
                    <%= f.date_field :date, class: "form-control" %>
                </div>

                <div class="mb-3">
                    <%= f.label :climbing_type, 'Select Climbing Style', class: "form-label" %>
                    <%= f.select :climbing_type, ['Sport', 'Trad', 'Bouldering'], {}, class: 'form-control' %>
                </div>

                <div class="mb-3">
                    <%= f.label :location, 'Where did you go climbing?', class: "form-label" %>
                    <%= f.text_area :location, rows: 2, style: "width: 80%;" ,class: "form-control" %>
                </div>

                <div class="mb-3">
                    <%= f.label :main_image, 'Upload an image' %>
                    <%= f.file_field :main_image %>
                </div>

                <div class="individual_outdoor_climbs">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Climb Name</th>
                            <th>Grade</th>
                            <th>Climbing Style</th>
                            <th>Climbing Partner</th>
                            <th>Notes</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <%= f.fields_for :individual_outdoor_climbs do |individual_outdoor_climb| %>
                            <tr class="nested-fields">

                            <td><%= individual_outdoor_climb.text_field :climb_name, class: "form-control", labelledby: "Climb Name form field" %></td>
                            <td><%= individual_outdoor_climb.text_field :grade, class: "form-control", label: "Climb grade form field" %></td>
                            <td><%= individual_outdoor_climb.text_field :climbing_style, class: "form-control" , label: "Climbin Style form field"%></td>
                            <td><%= individual_outdoor_climb.text_field :climbing_partner, class: "form-control", label: "Climb Partner form field" %></td>
                            <td><%= individual_outdoor_climb.text_field :notes, class: "form-control", label: "Climb Notes form field"  %></td>
                            <td><%= link_to_remove_association "Delete this climb", individual_outdoor_climb, class: "btn btn-secondary mt-3" ,  style:"background-color:#5b52bc; border-color:#5b52bc; color: white;", label: "Delete climb column" %></td>
                            </tr>
                        <% end %>
                        </tbody>
                    </table>
                    </div>

                <%# <%= link_to_add_association "Add Climb", f, :individual_outdoor_climbs, data: { association_insertion_node: '.individual_outdoor_climbs tbody', association_insertion_method: :append }, class: "btn btn-primary mt-3" %>
                <%= link_to_add_association "Add a new climb to the log", f, :individual_outdoor_climbs, data: { association_insertion_node: '.individual_outdoor_climbs', association_insertion_method: :append, wrap_object: 'td' }, class: "btn btn-light mt-3" %>
                                 
                
                <%# <section class="py-5 text-center container">
                <div class="row py-lg-5">
                    <div class="col-lg-6 col-md-8 mx-auto">

                    <%= form_with(model: @image, local: true, html: { multipart: true }) do |form| %>
                    <%# <div class="form-group"> %>
                        <%# <%= form.label :title, class: "control-label" %> 
                        <%# <%= form.text_field :title, class: "form-control" %> 
                    <%# </div> %>
                    <%# <div class="form-group"> %>
                        <%# <%= form.label :image, class: "control-label" %> 
                        <%# <%= form.file_field :image, class: "form-control" %> 
                    <%# </div> %>
                    <%# <%= form.submit "Upload", class: "btn btn-primary" %> 
                    <%# <% end %>
                    <br>
            <%= f.submit "Save Climb", class: "btn btn-secondary mt-3", style:"background-color:#5b52bc; border-color:#5b52bc; color: white;" %>
            <% end %> 
        </div>
       
        <%= button_to "Delete entire log", log_outdoor_climb_path(OutdoorClimbing.find(params[:id])), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "btn btn-secondary mt-3"%>
       
        <!-- </div> -->
    </section>
</main>

app/views/log_outdoor_climbs/filter.html.erb
<main>
    <section class="py-5 text-left container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Previous Outdoor Climbing Sessions</h1>
                <%# <%= debug @log_climbs %> 
                <%= debug(params)%>
                <form action="<%= filter_log_outdoor_climbs_path %>" method="get" class="mb-3">
                    <div class="input-group">
                        <select class="form-select" name="climbing_type">
                            <option value="all">All</option>
                            <option value="trad">Trad</option>
                            <option value="bouldering">Bouldering</option>
                            <option value="sport">Sport</option>
                        </select>
                        <button type="submit" class="btn btn-primary">Filter</button>
                    </div>
                </form>

                <% if user_signed_in? %>
                    <ul class="list-group">
                        <%# <% @log_climbs = OutdoorClimbing.order(date: :desc) %> 
                        <% @log_climbs.each do |log_climb| %>
                            <li class="list-group-item">
                                <%= log_climb.date %> - <%= log_climb.location %> - <%= log_climb.climbing_type %>
                                <%= link_to "Edit", edit_log_outdoor_climb_url(log_climb), class: "btn btn-primary btn-sm mx-2" %> 
                                <%# <%= link_to 'Delete', log_climb, method: :delete %>
                                <ul>
                                    <% if log_climb.individual_outdoor_climbs.present? %>
                                        <% log_climb.individual_outdoor_climbs.each do |individual_outdoor_climb| %>
                                            <li>
                                                <%= individual_outdoor_climb.climb_name %> - <%= individual_outdoor_climb.grade %>
                                            </li>
                                        <% end %>
                                    <% else %>
                                        <li>No individual outdoor climbs logged for this session.</li>
                                    <% end %>
                                </ul>
                            </li>
                        <% end %>
                    </ul>
                    <%# <p class="lead text-muted">Looks like you haven't logged any outdoor climbs,<br> %>
                        <%= link_to "log a new climbing session here", new_log_outdoor_climb_path, class: "btn btn-primary mt-3" %>
                    </p>
                <% else %>
                    <p class="lead text-muted">Please sign in to see previous logged climbs.
                        <%= link_to "Login", new_user_session_path, class: "btn btn-primary mt-3" %></p>
                <% end %>
            </div>
        </div>
    </section>
</main>

app/views/log_outdoor_climbs/index.html.erb
<main>
    <section class="py-5 text-left container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Previous Outdoor Climbing Sessions</h1>
                <br>
                <div class="text-center">
                <% if user_signed_in? %>

                    <p> Here's where you can see all of your previously logged climbs</p>
                    <p> If there isn't an option to 'add a climb' on your log, that's because there's already an image attached to that climb.</p>
                    <p> To change the image, just go to 'edit' and upload your new image there.</p>


                    
                    <br>
                    
                
                    <%= link_to "Log a new climbing session here", new_log_outdoor_climb_path, class: "btn btn-secondary c-2" , style:"background-color:#5b52bc; border-color:#5b52bc; color: white; width: 100%;"%>
                </div>
                <br>    <br>
                <form action="<%= filter_log_outdoor_climbs_path %>" method="get" class="mb-3">
                    <div class="input-group">
                        <select class="form-select" name="climbing_type">
                            <option value="all">All</option>
                            <option climbing_type="trad">Trad</option>
                            <option climbing_type="bouldering">Bouldering</option>
                            <option climbing_type="sport">Sport</option>
                        </select>
                        <button type="submit" class="btn btn-light" style="background-color:#5b52bc; border-color:#5b52bc; color: white;">Filter</button>
                    </div>
                </form>

                
                  <% @log_climbs.where(user_id: current_user.id).each do |log_climb| %>
                    
                      <ul class="list-group">
                          <%# <% @log_climbs = OutdoorClimbing.order(date: :desc) %> 
                          <%# <% @log_climbs.each do |log_climb| %> 
                              <li class="list-group-item">
                                  <%= log_climb.date %> - <%= log_climb.location %> - <%= log_climb.climbing_type %>
                                    
                                    
                                  <%= button_to "Delete", log_outdoor_climb_path(log_climb), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete,class: "btn btn-light btn-sm float-end mx-2" %>
                                  <%= link_to "Edit", edit_log_outdoor_climb_url(log_climb), class: "btn btn-light btn-sm float-end mx-2" %> 
                                  <div class="text-end">
                                        <% if log_climb.main_image.attached? %>
                                            
                                        <%else%>
                                            <%= link_to "Add an Image", edit_log_outdoor_climb_url(log_climb), class: "btn btn-light btn-sm float-end mx-2" %> 
                                  
                                            <% end %>
                                        </div>
                                  <%# <%= link_to 'Delete', log_climb, method: :delete %>
                                  <ul>
                                      <% if log_climb.individual_outdoor_climbs.present? %>
                                          <% log_climb.individual_outdoor_climbs.each do |individual_outdoor_climb| %>
                                              <li>
                                                  <%= individual_outdoor_climb.climb_name %> - <%= individual_outdoor_climb.grade %>
                                              </li>
                                          <% end %>
                                      <% else %>
                                          <li>No individual outdoor climbs logged for this session.</li>
                                      <% end %>
                                  </ul>
                                 
                              </li>
                               
                          <%# <% end %> 
                      </ul>
                      <%# <p class="lead text-muted">Looks like you haven't logged any outdoor climbs,<br> %>
                      </p>
                      <%end%>
                <% else %>
                    <p class="lead text-muted">Please log in to see previous logged climbs.<br>
                        <%= link_to "Login", new_user_session_path, class: "btn btn-dark c-2" %></p>
                <% end %>

            
            </div>
        </div>
    </section>
</main>

app/views/log_outdoor_climbs/new.html.erb
<%# <script>
  document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('saveClimbButton').addEventListener('click', function(event) {
      event.preventDefault(); // Prevent the default form submission
      
      // Submit the climbing session form
      document.getElementById('log_climb_form').submit();

      // Submit the image upload form
      document.getElementById('image_upload_form').submit();
    });
  });
</script> %>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">  Log a new Outdoor Climbing Session </h1>
          
          
          </p>




          <% if user_signed_in? %>
            <%= form_with(model: @log_climb, url: log_outdoor_climbs_path, local: true, multipart: true) do |f| %>

            <%# <%= form_with(model: @log_climb, url: log_outdoor_climbs_path, id: "log_climb_form") do |f| %> 

              <div class="field">
                <%= f.label :date, 'When did you go climbing?' %>
                <%= f.date_field :date %>
              </div>
              <br>
              <div class="field">
                <%= f.label :climbing_type, 'Select Climbing Style' %>
              <%= f.select :climbing_type, ['Sport', 'Trad', 'Bouldering'], {}, class: 'form-control' %>
              <br>
              </div>

              <div class="field">
                <%= f.label :location, 'Where did you go climbing?' %>
                <p> e.g. Stanage Plantation, Peak District, UK </p>
                <%= f.text_area :location, rows: 2, style: "width: 80%;" %> <!-- Added inline style for width -->
              </div>

                <br>
              <div class="field">
                <%= f.label :main_image, 'Upload an image' %>
                <%= f.file_field :main_image %>
              </div>
              <br>
              <%= link_to_add_association "Add a climb", f, :individual_outdoor_climbs, data: {association_insertion_node: '.individual_outdoor_climbs', association_insertion_method: :append} ,class: "btn btn-light btn-sm mx-2" %>
                

              <div class="individual_outdoor_climbs">
                  <%= f.fields_for :individual_outdoor_climbs do |individual_outdoor_climb| %>
                  <%= render partial 'individual_outdoor_climb_fields', f: individual_outdoor_climb %>
              
            <% end %>
                </div>
                <br>
      
      <%# <section class="py-5 text-center container">
                <div class="row py-lg-5">
                    <div class="col-lg-6 col-md-8 mx-auto">

                    <%= form_with(model: @log_climb, local: true, html: { multipart: true }, id: "image_upload_form") do |form| %>

                    <%# <div class="form-group">
                        <%= form.label :main_image %>
                        <%# <%= form.file_field :main_image %> 
                    <%# </div> %> 
                    
                    <%# <%= f.submit "Upload", class: "btn btn-primary" %> 

                    <%# <% end %>  



           <%# <%= f.submit "Save Climb", class: "btn btn-dark mt-3" %> 
      
      <br>
      <br>

      <%= f.submit "Save Climb", class:"btn-primary border-0 rounded-pill shadow p-3", id: "saveClimbButton" , style:"background-color:#5b52bc; border-color:#5b52bc; color: white;" %>
      
      <br><br>
      <%= link_to "Back", :back, class: "btn btn-secondary" %>

    

    <% end %>

    <%else%>
    <p>Please login to see log new climbs.</p>
    <%= link_to "Login", new_user_session_path , style:"background-color:#5b52bc; border-color:#5b52bc; color: white;" %>
    
  <% end %>
  <br>

  <%# <div>
          <ul>
            <li>Mod</li>
            <li>Diff</li>
            <li>VD</li>
            <li>HVD</li>
            <li>S</li>
            <li>HS</li>
            <li>VS</li>
            <li>HVS</li>
            <li>E1</li>
            <li>E3</li>
            <li>E4</li>
            <li>E5</li>
            <li>E6</li>
            <li>E7</li>
            <li>E8</li>
            <li>E9</li>
            <li>E10</li>
            <li>E11</li>
            <!-- Add more valid trad grades as needed -->
          </ul>

          </div> %>

 
</div>








</p>
        </div>
      </div>
    </section>

app/views/log_outdoor_climbs/show.html.erb
<%= render 'map_climbs' %>