config/routes.rb
Rails.application.routes.draw do
 
  #get 'log_outdoor_climbs/new'
  #get 'log_outdoor_climbs/create'
  devise_for :users

  root 'pages#index'
  get 'pages/index'
  get '/gallery', to: 'pages#gallery'

  get '/climbingmap', to: 'pages#climbingmap'
 
  get '/analytics', to: 'pages#analytics'

  get '/timer', to: 'pages#timer'

  resources :log_outdoor_climbs, only: [:index, :new, :create, :edit, :update, :destroy, :show, :display] do
    collection do
      get :filter
    end
    member do
      delete :destroy_outdoor_climbing
    end
  end

  resources :individual_outdoor_climbs, only: [:index, :new, :create, :update, :destroy]

  # resources :images, only: [:index, :new, :show, :create, :destroy, :display]

end

app/views/shared/_navbar.html.erb
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
   
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to image_tag("GrippedLogo.png", alt: "Your Logo", style: "width: 120px; height: 90px;"), root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav"  aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="main_nav">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%= link_to "Climbing Logs", log_outdoor_climbs_path, class: "nav-item nav-link me-4" %>
          <%= link_to "Gallery", gallery_path, class: "nav-item nav-link me-4" %>    
          <%= link_to "Climbing Map", climbingmap_path, class: "nav-item nav-link me-4" %>
          <%= link_to "Analytics", analytics_path, class: "nav-item nav-link me-4" %>
          <%= link_to "Timer", timer_path, class: "nav-item nav-link me-4" %>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <%= link_to "Account", edit_user_registration_path, class: "nav-item nav-link me-4" %>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link me-4" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>




<%# <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  
    <%= link_to "gripped", root_path, class: "navbar-brand" %>
    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>
      <%# <%= link_to "Outdoor Climbing", log_outdoor_climbs_path, class: "nav-item nav-link"  %>
      <%# </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%# <%= link_to current_user.email, edit_user_registration_path, class: "nav-item nav-link" %> 
          <%# <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %> 
        <%# <% else %> 
          <%# <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %> 
          <%# <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %> 
        <%# <% end %> 
      <%# </ul> %>
    <%# </div> %>
  <%# </div> %>
<%# </nav> %> 