config/routes.rb
Rails.application.routes.draw do
 
  #get 'log_outdoor_climbs/new'
  #get 'log_outdoor_climbs/create'
  devise_for :users

  root 'pages#index'
  get 'pages/index'
  get '/gallery', to: 'pages#gallery'

  get '/climbingmap', to: 'pages#climbingmap'
 
  get '/analytics', to: 'pages#analytics'

  get '/timer', to: 'pages#timer'

  resources :log_outdoor_climbs, only: [:index, :new, :create, :edit, :update, :destroy, :show, :display] do
    collection do
      get :filter
    end
    member do
      delete :destroy_outdoor_climbing
    end
  end

  resources :individual_outdoor_climbs, only: [:index, :new, :create, :update, :destroy]

  # resources :images, only: [:index, :new, :show, :create, :destroy, :display]

end

app/views/pages/_displayrecent.html.erb
<% if user_signed_in? %>

  <div class="container">
    <div class="row">
      <% index = 0 %>
      <% @log_climbs.where(user_id: current_user.id).each do |log_climb| %>
        <% if log_climb.main_image.attached? && index < 3 %>
          <% index += 1 %>
          <div class="col-md-4 mb-4">
            <div class="card">
              <%= image_tag log_climb.main_image, class: "card-img-top" , alt: "user upload image"%>
              <div class="card-body">
                <h2 class="card-title"><%= log_climb.date %></h2>
                <p class="card-text"><%= log_climb.location %> - <%= log_climb.climbing_type %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/pages/analytics.html.erb
<% if user_signed_in? %>
  <div class="container text-center my-5">
    <div class="row">
      <div class="col-md-12">
        <h1 class="fw-light mb-4">Your Climbing Summary</h1>
        <h2> Let's take a look on your climbing summary </h2> <br>
      </div>
    </div>

    <%= form_tag(analytics_path, method: :get, class: "mb-4") do %>
      <%= label_tag(:time_period, "Select Time Period:") %>
      <%= select_tag(:time_period, options_for_select(["All Logs","This Week", "This Month", "This Year"], params[:time_period]), class: "form-select") %> <br>
      <%= submit_tag("Filter", class: "btn btn-primary", style:"background-color:#5b52bc; border-color:#5b52bc; color: white;") %>
    <% end %>



    
  </div>
<% end %>


<script>
<%trad_grades_uk = {
  "Mod" => "Moderate",
  "Diff" => "Difficult",
  "VD" => "Very Difficult",
  "HVD" => "Hard Very Difficult",
  "MS" => "Mild Severe",
  "S" => "Severe",
  "HS" => "Hard Severe",
  "VS" => "Very Severe",
  "HVS" => "Hard Very Severe",
  "E1" => "Extreme 1",
  "E2" => "Extreme 2",
  "E3" => "Extreme 3",
  "E4" => "Extreme 4",
  "E5" => "Extreme 5",
  "E6" => "Extreme 6",
  "E7" => "Extreme 7",
  "E8" => "Extreme 8",
  "E9" => "Extreme 9",
  "E10" => "Extreme 10",
  "E11" => "Extreme 11",
  "E12" => "Extreme 12",
  "E13" => "Extreme 13",
  "E14" => "Extreme 14",
  "E15" => "Extreme 15",
  "E16" => "Extreme 16",
  "E17" => "Extreme 17",
  "E18" => "Extreme 18",
  "E19" => "Extreme 19",
  "E20" => "Extreme 20"
}%>

<% french_grades = [
  "1", "2", "3", "4a", "4b", "4c",
  "5a", "5b", "5c", "6a", "6a+", "6b",
  "6b+", "6c", "6c+", "7a", "7a+", "7b",
  "7b+", "7c", "7c+", "8a", "8a+", "8b",
  "8b+", "8c", "8c+", "9a", "9a+", "9b",
  "9b+", "9c" , "9c+"
] %>

</script>
<% hardest_trad_grade_uk = nil %>
<% hardest_sport_grade_uk = nil %>
<% hardest_bouldering_grade_uk = nil %>

<% @log_climbs_filtered.each do |climb| %>
    <% if climb.individual_outdoor_climbs.any? %>
  
        <% climb.individual_outdoor_climbs.each do |individual_climb| %>
            <%if individual_climb.grade.present?%>
                <% grade = individual_climb.grade %>
            
                <% if climb.climbing_type == "Trad"%>
                    <% if trad_grades_uk.include?(grade) %>
                
                        <% if hardest_trad_grade_uk.nil? || trad_grades_uk[grade] > trad_grades_uk[hardest_trad_grade_uk] %>
                        <% hardest_trad_grade_uk = grade %>
                        <% end %>
                    <%end%>

                <% elsif climb.climbing_type == "Bouldering" %>
                    <% if french_grades.include?(grade) %>
                            <% if hardest_bouldering_grade_uk.nil? || french_grades.index(grade) > french_grades.index(hardest_bouldering_grade_uk) %>
                            <% hardest_bouldering_grade_uk = grade %>
                        <% end %>
                    <% end %>
                <% elsif climb.climbing_type == "Sport" %>
                    <% if french_grades.include?(grade) %>
                        <% if hardest_sport_grade_uk.nil? || french_grades.index(grade) > french_grades.index(hardest_sport_grade_uk) %>
                        <% hardest_sport_grade_uk = grade %>
                        <% end %>
                    <% end %>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
<% end %>




<% if hardest_bouldering_grade_uk || hardest_sport_grade_uk || hardest_trad_grade_uk %>
  <div class="container text-center my-5">
    <h4>Climbing Grade Summary</h4>
    <table class="table">
      <thead>
        <tr>
          <th>Climbing Type</th>
          <th>Hardest Grade</th>
        </tr>
      </thead>
      <tbody>
        <% if hardest_bouldering_grade_uk %>
          <tr>
            <td>Bouldering</td>
            <td><%= hardest_bouldering_grade_uk %></td>
          </tr>
        <% else %>
          <tr>
            <td>Bouldering</td>
            <td>No valid bouldering climbing grades found</td>
          </tr>
        <% end %>

        <% if hardest_sport_grade_uk %>
          <tr>
            <td>Sport</td>
            <td><%= hardest_sport_grade_uk %></td>
          </tr>
        <% else %>
          <tr>
            <td>Sport</td>
            <td>No valid sport climbing grades found</td>
          </tr>
        <% end %>

        <% if hardest_trad_grade_uk %>
          <tr>
            <td>Trad</td>
            <td><%= hardest_trad_grade_uk %></td>
          </tr>
        <% else %>
          <tr>
            <td>Trad</td>
            <td>No valid trad climbing grades found</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="container text-center my-5">
    <h3>No valid climbing grades found in your climbs.</h3>
  </div>
<% end %>
<div class="container text-center my-5">
    <div class="row">
      <div class="col-md-12">
        
        <h3> Climbing Split </h3> <br>
      </div>
    </div>

<%= pie_chart @log_climbs_filtered.where(user_id: current_user.id).group(:climbing_type).count %>

<div class="container text-center my-5">
    <div class="row">
      <div class="col-md-12">
        
        <h3> Climbing Log Timeline </h3> <br>
        <h4> Let's have a look at how many climbing sessions you've logged </h4>
      </div>
    </div>
    <%= line_chart @log_climbs_filtered.group_by_day(:date).count %>

app/views/pages/climbingmap.html.erb
<!DOCTYPE html>
<html>
<head><% if user_signed_in? %>
<div class="container text-center my-5">
    <div class="row">
        <div class="col-md-12">
            <h1 class="fw-light mb-4">Your Climbing Map</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="alert alert-info" role="alert">
                Click on the markers to see more details about the climbing session.<br><br>
            </div>
        </div>
        <div class="col-md-6">
            <div class="alert alert-info" role="alert" >
                Marker missing or it isn't where you think it should be? Add some more details of the climbing location in your log.<br?>
                <a href="log_outdoor_climbs" class="btn-sml btn-light my-2">Go to your Logs</a>
            </div>
        </div>
    </div>
   
     <script>
    document.addEventListener("turbo:load", function() {
        document.getElementById('map').addEventListener("turbo:submit-end", function(e){
            window.location.reload(true);
        });
    });
    </script>

   
    <meta charset="utf-8">
   
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.js"></script>
    <style>
    body { margin: 10; padding: 70; }
    #map { position: absolute; top: 10; bottom: 10; width: 75%; height: 600px}
    </style>
    </head>
    <body>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">

    <style>
        #geocoder-container > div {
            min-width: 50%;
            margin-left: 25%;
        }
    </style>
    <div id="map"></div>





    <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoiYWZzbWl0aDEyMyIsImEiOiJjbG9pdTIyaGsxcHd3MnNydzltZnl2Y2Q2In0.uNEZOI46PYjl40gzZ0U2vw';
        const map = new mapboxgl.Map({
            container: 'map',
            // Choose from Mapbox's core styles, or make your own style with Mapbox Studio
            style: 'mapbox://styles/mapbox/outdoors-v12',
            center: [-1.6253621, 53.2684064],
            zoom: 0
        });

        
        
        const logClimbsCoordinates = <%= raw @log_climbs.where(user_id: current_user.id).to_json(only: [:longitude, :latitude]) %>;

    // Log the coordinates to the console for debugging
    

        // Filter out null values in case when you log a climb, the geocoder doesn't find coordinates
        const filteredCoordinates = logClimbsCoordinates.filter(coords => coords.longitude !== null && coords.latitude !== null);
            
        // Add markers to the map
        filteredCoordinates.forEach(coords => {
    const marker = new mapboxgl.Marker()
        .setLngLat([coords.longitude, coords.latitude])
        .addTo(map);


        marker.getElement().addEventListener('dblclick', () => {
        map.flyTo({
            center: [coords.longitude, coords.latitude],
            zoom: 100, // Adjust the zoom level as needed
            essential: true // This option ensures that the flyTo animation is not interrupted by user events
        });
        })

    const climbDetails = <%= raw @log_climbs.where(user_id: current_user.id).to_json(only: [:longitude, :latitude, :location, :date, :climbing_type]) %>;

    const matchingClimb = climbDetails.find(climbDetails => climbDetails.longitude === coords.longitude && climbDetails.latitude === coords.latitude);

    console.log('filteredCoordinates:', filteredCoordinates);
    console.log('climb details:', climbDetails);
    console.log('matchingClimb:', matchingClimb);

    if (matchingClimb) {
        const popup = new mapboxgl.Popup()
            .setHTML(
                `<p>${matchingClimb.date}</p>
                 <p>${matchingClimb.location}</p>
                 <p>${matchingClimb.climbing_type}</p>
                 `
            );

        // Attach the popup to the marker
        marker.setPopup(popup);
    }
    
});


        const bounds = new mapboxgl.LngLatBounds();
        filteredCoordinates.forEach(coords => {
            bounds.extend([coords.longitude, coords.latitude]);
        });

        // Set map center and zoom level to fit the bounds
        map.fitBounds(bounds, { padding: 50 });

        map.addControl(new mapboxgl.NavigationControl());

    </script>
    <%else%>
        <p class="lead text-muted">Please sign in to see previous logged climbs.<br>
        <%= link_to "Login", new_user_session_path, class: "btn btn-dark c-2" %></p>
    <% end %></div>
    </div>
</div></div>
    </body>
    </section>
    </html>

app/views/pages/gallery.html.erb
 <section class="text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">  Welcome to your Climbing Gallery </h1>
        </div>
      </div>
    </section>

<% if user_signed_in? %>
<section class="text-center container">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <p class="card-text">To add a new image to the gallery, first log a new climbing session and attach the image to the session.</p>
          <%= link_to "Log a new climbing session here", new_log_outdoor_climb_path, class: "btn btn-secondary c-2" , style:"background-color:#5b52bc; border-color:#5b52bc; color: white; width: 100%;"%> 
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <p class="card-text">To add or replace an image to an existing climbing session, edit your previous session and add an image</p>
          <%= link_to "See your previous climbs here", log_outdoor_climbs_path, class: "btn btn-secondary c-2", style:"background-color:#5b52bc; border-color:#5b52bc; color: white; width: 100%;" %>
        </div>
      </div>
    </div>
  </div>
</section>
<br>

  <div class="container">
    <div class="row">
      <% @log_climbs.where(user_id: current_user.id).each do |log_climb| %>
        <% if log_climb.main_image.attached? %>
          <div class="col-md-4 mb-4">
            <div class="card">
              <%= image_tag log_climb.main_image, class: "card-img-top" , alt: "user upload image"%>
              <div class="card-body">
                <h5 class="card-title"><%= log_climb.date %></h5>
                <p class="card-text"><%= log_climb.location %> - <%= log_climb.climbing_type %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <%else%>
    <p class="lead text-muted">Please sign in to see previous logged climbs.<br>
    <%= link_to "Login", new_user_session_path, class: "btn btn-dark c-2" %></p>
<% end %>

app/views/pages/index.html.erb
  <main>
    <section class="py-5 text-center container">
      <%= image_tag('GrippedLogo.png', alt: 'Gripped Logo', class: 'rounded-circle img-fluid w-50') %>

     
          
          <br>
          <% if user_signed_in? %>
        

        
          <h1>Welcome, </h1>
          <h1><%= current_user.email%> </h1>
          


        
          <p class="lead text-muted">Start logging your climbing sessions here and track your progress.</p>
          <div class="row text-center">
  <div class="col-md-6 mb-4">
    <a href="log_outdoor_climbs/new" class="btn btn-secondary btn-lg" style="width: 100%;">Log a New Outdoor Climbing Session</a>
  </div>
  <div class="col-md-6 mb-4">
    <a href="log_outdoor_climbs" class="btn btn-secondary btn-lg" style="width: 100%;">See Your Previous Climbs</a>
  </div>
  <div class="col-md-6 mb-4">
    <%= link_to "Explore Your Climbing Map", climbingmap_path, class: "btn btn-secondary btn-lg c-2", style: "width: 100%;" %>   
  </div>
  <div class="col-md-6 mb-4">
    <%= link_to "View Your Gallery", gallery_path, class: "btn btn-secondary btn-lg c-2", style:" width: 100%;" %>
  </div>
</div>






    </section>

    <%= render '/pages/displayrecent', log_climbs: @log_climbs %>
  </main>


<% else %>
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h5 class="text-white h4">Menu</h5>
      <span class="text-muted">Explore the menu.</span>
    </div>
  </div>

  <main>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">  Welcome </h1>
          <p class="lead text-muted">Sign in to start logging your climbing sessions and track your progress.</p>
          <a href="users/sign_in" class="btn btn-dark my-2">Log in</a>
          <a href="users/sign_up" class="btn btn-dark my-2">Sign Up</a>
          <p>
          
  
  
<% end %>

        </div>
      </div>
    </section>

app/views/pages/timer.html.erb
<!DOCTYPE HTML>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        p {
            text-align: center;
            font-size: 60px;
            margin-top: 0px;
        }
    </style>
</head>

<body>

    <label for="effortDuration">Effort Time (seconds):</label>
    <input type="number" id="effortDuration" value="5">
    <br>

    <label for="restDuration">Rest Time (seconds):</label>
    <input type="number" id="restDuration" value="30">
    <br>

    <label for="maxReps">Number of Reps:</label>
    <input type="number" id="maxReps" value="6">
    <br>

    <label for="maxSets">Number of Sets:</label>
    <input type="number" id="maxSets" value="1">
    <br>

    <p id="timerDisplay"></p>
    <p id="setCounter">Set: 0</p>
    <p id="repCounter">Reps: 0</p>

    <!-- Buttons to control the timer -->
    <button onclick="startWorkout()">Start Workout</button>
    <button onclick="pauseResumeWorkout()" id="pauseResumeBtn" style="display: none;">Pause</button>
    <button onclick="resetWorkout()">Reset</button>

    <script>
        var setCounter = 0;
        var repCounter = 0;
        var timer;
        var isPaused = false;
        var timeLeft = 0; // Variable to store time left in seconds
        var isEffort = false; // Flag to track if it's an effort period

        function pauseResumeWorkout() {
            if (isPaused) {
                document.getElementById("pauseResumeBtn").innerHTML = "Pause";
                startWorkoutTimer();
            } else {
                document.getElementById("pauseResumeBtn").innerHTML = "Resume";
                isPaused = true;
                clearTimeout(timer);
            }
        }

        function resetWorkout() {
            isPaused = false;
            clearTimeout(timer);
            document.getElementById("timerDisplay").innerHTML = "00m 00s";
            document.getElementById("setCounter").innerHTML = "Set: 0";
            document.getElementById("repCounter").innerHTML = "Reps: 0";
            document.getElementById("pauseResumeBtn").style.display = "none";
            document.getElementById("pauseResumeBtn").innerHTML = "Pause";
            document.querySelector('button').disabled = false;
            setCounter = 0;
            repCounter = 0;
            timeLeft = 0;
            isEffort = false; // Reset to the initial state
        }

        function updateCountdown() {
            var minutes = Math.floor(timeLeft / 60);
            var seconds = timeLeft % 60;
            document.getElementById("timerDisplay").innerHTML = (minutes < 10 ? '0' : '') + minutes + "m " + (seconds < 10 ? '0' : '') + seconds + "s ";
            document.getElementById("setCounter").innerHTML = "Set: " + setCounter;
            document.getElementById("repCounter").innerHTML = "Reps: " + repCounter;
        }

        function startWorkout() {
            var effortDuration = parseInt(document.getElementById("effortDuration").value, 10) || 10;
            var restDuration = parseInt(document.getElementById("restDuration").value, 10) || 30;
            var maxReps = parseInt(document.getElementById("maxReps").value, 10) || 6;
            var maxSets = parseInt(document.getElementById("maxSets").value, 10) || 1;

            document.querySelector('button').disabled = true;
            isPaused = false;

            // Initial 10-second countdown
            function initialCountdown() {
                if (timeLeft === 0) {
                    clearTimeout(timer);
                    // Start the workout after the initial countdown
                    startWorkoutTimer();
                } else {
                    updateCountdown();
                    timeLeft--;
                    document.getElementById("timerDisplay").style.color = "orange"; // Initial countdown color
                    timer = setTimeout(initialCountdown, 1000);
                }
            }

            resetWorkout(); // Reset before starting
            timeLeft = 10; // Set the initial countdown time
            initialCountdown();

            // Main workout timer
            function startWorkoutTimer() {
                document.getElementById("pauseResumeBtn").style.display = "inline"; // Show the Pause/Resume button
                function nextStep() {
                    if (isPaused) {
                        return;
                    }

                    if (timeLeft === 0) {
                        if (!isEffort) {
                            // If it's a rest period, switch to effort
                            isEffort = true;
                            timeLeft = effortDuration;
                            repCounter++;
                            document.getElementById("timerDisplay").style.color = "green"; // Effort color
                        } else {
                            // If it's an effort period, switch to rest
                            if (repCounter < maxReps) {
                                timeLeft = restDuration;
                                document.getElementById("timerDisplay").style.color = "red"; // Rest color
                            } else if (setCounter < maxSets - 1) {
                                // Rest period between sets
                                repCounter = 0;
                                setCounter++;
                                timeLeft = restDuration;
                                document.getElementById("timerDisplay").style.color = "red"; // Rest color
                            } else {
                                // Last set, no rest
                                setCounter++;
                                timeLeft = effortDuration;
                                document.getElementById("timerDisplay").style.color = "green"; // Effort color
                            }
                            isEffort = false;
                        }
                    }

                    updateCountdown();
                    timeLeft--;
                    timer = setTimeout(nextStep, 1000);
                }

                nextStep(); // Start the main workout timer
            }
        }
    </script>

</body>

</html>